# Install: `cargo install cargo-make`
# Help: https://sagiegurari.github.io/cargo-make/

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = true
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = true

# -----------------------------------------------------------------------------
# Build and test
# -----------------------------------------------------------------------------

[tasks.clean]
args = ["clean"]
command = "cargo"

[tasks.build]
args = ["build"]
command = "cargo"
dependencies = ["clean"]

[tasks.test]
args = ["nextest", "run"]
command = "cargo"
dependencies = ["clean"]
env = { RUSTFLAGS = "-Dwarnings" }

# -----------------------------------------------------------------------------
# Basic hygiene
# -----------------------------------------------------------------------------

[tasks.fmt]
args = ["fmt", "--all"]   # "--", "--emit=files"]
command = "cargo"
install_crate = "rustfmt"

[tasks.lint]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
args = ["clippy", "--", "-Dclippy::all", "-Dclippy::nursery", "-Dclippy::pedantic"]
command = "cargo"
install_crate = { rustup_component_name = "clippy" }

[tasks.audit]
args = ["audit"]
command = "cargo"

[tasks.unused]
args = ["machete", "--skip-target-dir"]
command = "cargo"
install_crate = "cargo-machete"

[tasks.outdated]
args = ["outdated", "--workspace", "--exit-code", "1"]
command = "cargo"
install_crate = "cargo-outdated"

[tasks.check]
dependencies = ["fmt", "lint", "audit", "outdated", "unused"]

# -----------------------------------------------------------------------------
# Publishing
# -----------------------------------------------------------------------------

[tasks.breaking]
args = ["semver-checks"]
command = "cargo"
install_crate = "cargo-semver-checks"

[tasks.pre-pub]
run_task = [{ name = "pre-pub-core", parallel = true }, { name = "pre-pub-vci", parallel = true }]

[tasks.pre-pub-pkg]
args = ["publish", "--dry-run", "--allow-dirty"]
command = "cargo"

[tasks.pre-pub-core]
args = ["--package", "vercre-core"]
extend = "pre-pub-pkg"

[tasks.pre-pub-vci]
args = ["--package", "vercre-vci"]
extend = "pre-pub-pkg"

[tasks.pre-pub-vp]
args = ["--package", "vercre-vp"]
extend = "pre-pub-pkg"

[tasks.pre-pub-wallet]
args = ["--package", "vercre-wallet"]
extend = "pre-pub-pkg"